LIBS7_VERSION = "0.1.0"
LIBTOML_CC_VERSION = "0.1.0"
TOML_S7_VERSION = "0.1.0"

GOPT_VERSION = "10.0.0"
LIBLOG_CC_VERSION = "1.0.0"
UNITY_VERSION = "2.5.2"
UTHASH_VERSION = "2.3.0"

BASE_SRCS = ["//config:config.h", "//config:ansi_colors.h"]
BASE_DEPS = []
BASE_INCLUDE_PATHS = []
BASE_COPTS = []
BASE_DEFINES = []
BASE_LINKOPTS = []
