load("@cc_config//:CONFIG.bzl",
     _BASE_COPTS    = "BASE_COPTS",
     _BASE_DEFINES  = "BASE_DEFINES",
     _BASE_LINKOPTS = "BASE_LINKOPTS")

load("@libs7//config/cc:CONFIG.bzl",
     _BASE_SRCS           = "LIBS7_SRCS",
     _BASE_DEPS           = "LIBS7_DEPS",
     _BASE_INCLUDE_PATHS  = "LIBS7_INCLUDE_PATHS")

BASE_COPTS = _BASE_COPTS
BASE_LINKOPTS = _BASE_LINKOPTS
BASE_DEFINES = _BASE_DEFINES

BASE_SRCS = _BASE_SRCS
BASE_DEPS = _BASE_DEPS
BASE_INCLUDE_PATHS = _BASE_INCLUDE_PATHS
